# Generated by Django 5.0.7 on 2026-07-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(choices=[('construction', 'Construction'), ('healthcare', 'Healthcare'), ('automotive', 'Automotive'), ('fitness', 'Fitness'), ('finance', 'Finance'), ('retail', 'Retail'), ('other', 'Other')], default='retail', max_length=50)),
                ('industry_display', models.CharField(blank=True, help_text='e.g. Retail • Fashion', max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/logos/')),
                ('logo_url', models.URLField(blank=True, help_text='Optional direct image URL if not uploading file')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('since', models.CharField(default='2024', max_length=20)),
                ('instagram', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('image_url', models.URLField(blank=True, help_text='Optional direct photo URL')),
                ('description', models.TextField()),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('icon_class', models.CharField(default='bi-globe', help_text='Bootstrap icon class e.g. bi-pencil-square', max_length=100)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
